version: '3.8'

services:
    php:
        build: docker/php
        volumes:
            - ./app:/srv/app

    nginx:
        platform: linux/arm64
        image: nginx:1.23.3-alpine
        working_dir: /srv/app
        depends_on:
            - php
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./app/public:/srv/app/public
        ports:
            - '80:80'

    mysql:
        platform: linux/arm64
        image: mysql:8.0.32
        volumes:
            - mysql-storage:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=reservations
        ports:
            - '3306:3306'
        depends_on:
            - php

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        ports:
            - '18080:80'
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=pass

volumes:
    mysql-storage:
